version: '3'
services:
  did:
    build:
      context: .
      dockerfile: ./did/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "dev" ]

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "dev" ]
  #  frontend:
  #    build:
  #      context: .
  #      dockerfile: ./frontend/Dockerfile
  #    ports:
  #      - "8081:8081"
  #    environment:
  #      - NODE_ENV=development
  #    command: [ "npm", "start" ]
  service-provider:
    build:
      context: .
      dockerfile: ./service-provider/Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "dev" ]

  issuer:
    build:
      context: .
      dockerfile: ./issuer/Dockerfile
    ports:
      - "3210:3210"
    environment:
      - NODE_ENV=development
    command: [ "npm", "run", "dev" ]
  cli:
    build:
      context: .
      dockerfile: ./cli/Dockerfile
