name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Run ESLint for backend
        working-directory: backend
        run: npm run lint

      - name: Run Jest tests for backend
        working-directory: backend
        run: npm test

  service-provider:
    name: Service Provider
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install service provider dependencies
        working-directory: service-provider
        run: npm install

      - name: Run ESLint for service provider
        working-directory: service-provider
        run: npm run lint

      - name: Install libraries dependencies
        working-directory: service-provider
        run: npm install --prefix ../lib

      - name: Run Jest tests for service provider
        working-directory: service-provider
        run: npm test

  did:
    name: DID Web Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install DID dependencies
        working-directory: did
        run: npm install

      - name: Run ESLint for backend
        working-directory: did
        run: npm run lint

      - name: Run Jest tests for backend
        working-directory: did
        run: npm test

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run ESLint for frontend
        working-directory: frontend
        run: npm run lint

      - name: Run Jest tests for frontend
        working-directory: frontend
        run: npm test

  issuer:
    name: Issuer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install libraries dependencies
        working-directory: issuer
        run: npm install

      - name: Run ESLint for issuer
        working-directory: issuer
        run: npm run lint

      - name: Install libraries dependencies
        working-directory: service-provider
        run: npm install --prefix ../lib

      - name: Run Jest tests for issuer
        working-directory: issuer
        run: npm test

  libraries:
    name: Libraries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install libraries dependencies
        working-directory: lib
        run: npm install

      - name: Run ESLint for libraries
        working-directory: lib
        run: npm run lint

      - name: Run Jest tests for libraries
        working-directory: lib
        run: npm test
